steps:
    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/authen-service', '.']
    # push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/authen-service']
    # Deploy container image to Cloud Run : Test Environment
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'authen-service', '--image', 'gcr.io/$PROJECT_ID/authen-service', '--region', 'asia-east1','--platform', 'managed', '--allow-unauthenticated']
    