version: '3'
services:
  db:
    image: mongo
    ports: 
      - "27017:27017"
    deploy:
      replicas: 1
  
  authen-service:
    image: authen-service:0.1
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/myapp
    deploy:
      replicas: 1